name: App workflow DEVELOP
run-name: app-deploy-DEVELOP

on: 
  push:
    branches:
      - develop
      - feat/*
  pull_request:
    branches:
      - develop

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  ### Makes a call to the workflow template defined to execute terraform, in this case the variables define the develop environment
  infra-deploy:
    uses: danielrive/devoteam-load-generator/.github/workflows/service-build-push-template.yaml@develop
    with: 
      ENVIRONMENT: 'develop'
      PROJECT_NAME: 'load-generator'

