name: build-app

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string 
     
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        id: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        id: set-up-qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: set-up-buildx
        uses: docker/setup-buildx-action@v2
      - name: Build containter
        id: build
        working-directory: '/'
        run: |

            COMMIT_ID=${{ github.sha}}

            SHORT_COMMIT_ID="${COMMIT_ID:0:6}"
            
            echo "${{ github.ref }}"

            docker buildx build -t ${{ env.PROJECT_NAME }}:${{ inputs.ENVIRONMENT }} --file ./Dockerfile  --platform linux/amd64 .

